version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    container_name: myweb-proxy
  express:
    image: express-server
    container_name: express
    ports:
      - 3000:3000
    restart: unless-stopped
  fastapi:
    image: fastapi-server
    container_name: fastapi
    ports:
      - 8000:8000